-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 16:26:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema green_laundry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema green_laundry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `green_laundry` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `green_laundry` ;

-- -----------------------------------------------------
-- Table `green_laundry`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`member` (
  `id_member` INT NOT NULL AUTO_INCREMENT,
  `no_hp` VARCHAR(13) CHARACTER SET 'armscii8' NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `nama` MEDIUMTEXT NOT NULL,
  `alamat` MEDIUMTEXT NOT NULL,
  `foto` LONGBLOB NULL,
  `tier_member` INT NOT NULL,
  `total_laundry` INT NULL,
  `total_harga` INT NULL,
  PRIMARY KEY (`id_member`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `no_hp_UNIQUE` ON `green_laundry`.`member` (`no_hp` ASC);


-- -----------------------------------------------------
-- Table `green_laundry`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`admin` (
  `id_admin` VARCHAR(10) NOT NULL,
  `password` VARCHAR(16) NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_laundry`.`kupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`kupon` (
  `id_kupon` INT NOT NULL AUTO_INCREMENT,
  `kode_kupon` VARCHAR(10) NOT NULL,
  `judul_kupon` MEDIUMTEXT NOT NULL,
  `masa_berlaku` DATE NOT NULL,
  `keterangan` MEDIUMTEXT NOT NULL,
  `min_laundry` INT NOT NULL,
  `persentase_diskon` INT NOT NULL,
  `tier_kupon` INT NOT NULL,
  `jumlah_klaim` INT NULL,
  `admin_id_admin` VARCHAR(10) NULL,
  PRIMARY KEY (`id_kupon`, `admin_id_admin`),
  CONSTRAINT `fk_kupon_silver_admin1`
    FOREIGN KEY (`admin_id_admin`)
    REFERENCES `green_laundry`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_kupon_silver_admin1_idx` ON `green_laundry`.`kupon` (`admin_id_admin` ASC);

CREATE UNIQUE INDEX `kode_kupon_UNIQUE` ON `green_laundry`.`kupon` (`kode_kupon` ASC);


-- -----------------------------------------------------
-- Table `green_laundry`.`kupon_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`kupon_member` (
  `id_member` INT NOT NULL AUTO_INCREMENT,
  `id_kupon` INT NOT NULL,
  `kode_kupon` VARCHAR(10) NULL,
  `persentase_diskon` INT NULL,
  `min_laundry` VARCHAR(45) NULL,
  `masa_berlaku` DATE NULL,
  `terpakai` TINYINT NULL,
  PRIMARY KEY (`id_member`),
  CONSTRAINT `id_member_kupon`
    FOREIGN KEY (`id_member`)
    REFERENCES `green_laundry`.`member` (`id_member`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_kupon`
    FOREIGN KEY (`id_kupon`)
    REFERENCES `green_laundry`.`kupon` (`id_kupon`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `no_hp_UNIQUE` ON `green_laundry`.`kupon_member` (`kode_kupon` ASC);

CREATE INDEX `id_kupon_idx` ON `green_laundry`.`kupon_member` (`id_kupon` ASC);


-- -----------------------------------------------------
-- Table `green_laundry`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`order` (
  `id_member` INT NULL,
  `no_hp` VARCHAR(13) NOT NULL,
  `nama` MEDIUMTEXT NOT NULL,
  `alamat` MEDIUMTEXT NOT NULL,
  `jenis_barang` MEDIUMTEXT NOT NULL,
  `note` LONGTEXT NULL,
  `waktu_jemput` DATETIME NOT NULL,
  `kupon` VARCHAR(10) NULL,
  `berat` INT NULL,
  `harga` INT NULL,
  `admin_id_admin` VARCHAR(10) NULL,
  PRIMARY KEY (`id_member`, `admin_id_admin`),
  CONSTRAINT `id_member_order`
    FOREIGN KEY (`id_member`)
    REFERENCES `green_laundry`.`member` (`id_member`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_admin1`
    FOREIGN KEY (`admin_id_admin`)
    REFERENCES `green_laundry`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_admin1_idx` ON `green_laundry`.`order` (`admin_id_admin` ASC);


-- -----------------------------------------------------
-- Table `green_laundry`.`karyawan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`karyawan` (
  `id_karyawan` VARCHAR(10) NOT NULL,
  `tanggal_terdaftar` DATE NOT NULL,
  `nama` MEDIUMTEXT NOT NULL,
  `no_hp` VARCHAR(13) NOT NULL,
  `alamat` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_karyawan`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `no_hp_UNIQUE` ON `green_laundry`.`karyawan` (`no_hp` ASC);


-- -----------------------------------------------------
-- Table `green_laundry`.`presensi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_laundry`.`presensi` (
  `id_karyawan` VARCHAR(10) NOT NULL,
  `nama` MEDIUMTEXT NOT NULL,
  `status` TINYINT NOT NULL,
  `waktu_hadir` DATETIME NULL,
  `total_hadir` INT NULL,
  `total_tidakhadir` INT NULL,
  `admin_id_admin` VARCHAR(10) NULL,
  PRIMARY KEY (`id_karyawan`, `admin_id_admin`),
  CONSTRAINT `id_karyawan`
    FOREIGN KEY (`id_karyawan`)
    REFERENCES `green_laundry`.`karyawan` (`id_karyawan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presensi_admin1`
    FOREIGN KEY (`admin_id_admin`)
    REFERENCES `green_laundry`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_presensi_admin1_idx` ON `green_laundry`.`presensi` (`admin_id_admin` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
